### ISSUE TITLE
[Feature] Should we use git pre-commit hooks?

### ISSUE THREAD

**Issue by G-XD** [apache/incubator-paimon-webui#22]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon-webui/issues) and found nothing similar.

### Motivation

I found that we do not use pre-commit hooks to perform some checks or operations before committing code, such as code formatting, unit testing, code quality analysis, etc. This may lead to some inconsistent, erroneous or low-quality code being committed to the repository, affecting the maintainability and reliability of the project.

### Solution

I suggest that we use a `install-pre-commit-hooks.sh` script to install pre-commit hooks, which can automatically create a `pre-commit` file in the `.git/hooks/` and define the operations we want to perform in it. This way, every time we commit code, these operations will be automatically run and prevent the commit if any problems are found.

The advantages of using this script are:

- It can improve the consistency, correctness and quality of the code
- It can reduce human errors and omissions
- It can save time and energy, avoid repetitive work

The disadvantages of using this script are:

- It may cause git commits will take a little longer
- It may require making some modifications or adjustments according to different operating systems and shell environments

I would like to hear your opinions and feedback on this suggestion, whether you think this feature is useful and necessary, whether there are better methods or alternatives, and whether there are any potential problems or risks.

Or use [pre-commit](https://pre-commit.com/), but this library doesn't have good enough support for java.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by s7monk** [comment]
Will the advantages of using this script make submitting code more complicated? But if the complexity of submitting code is controllable, it can improve code maintainability and avoid submitting non-compliant code, I think it is feasible.

**Comment by G-XD** [comment]
> Will the advantages of using this script make submitting code more complicated? But if the complexity of submitting code is controllable, it can improve code maintainability and avoid submitting non-compliant code, I think it is feasible.

The git operation doesn't change anything, it just takes a little more time on `commit` action.

**Comment by s7monk** [comment]
can close
