### ISSUE TITLE
[Feature] Support Flink task submission

### ISSUE THREAD

**Issue by s7monk** [apache/incubator-paimon-webui#23]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon-webui/issues) and found nothing similar.

### Motivation

In order to allow users to write Flink SQL queries on the playground page to analyze Paimon data, we need to be able to submit Flink tasks to clusters such as standalone clusters or yarn sessions. Colleagues can also support the submission of Application tasks.

### Solution

We can integrate with Flink by connecting to Flink SQL Gateway or through API.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by hunter-cloud09** [comment]
Is anyone doing this task now？ take me one pls

**Comment by SteNicholas** [comment]
@hunter-cloud09, thanks for taking this issue. You could support this feature with @s7monk. I have assigned to @s7monk.
