### ISSUE TITLE
[Discussion] Positioning of the project

### ISSUE THREAD

**Issue by s7monk** [apache/incubator-paimon-webui#25]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon-webui/issues) and found nothing similar.

### Motivation

The official positioning of Apache Paimon is a streaming data lake platform. Since the positioning is as a platform, it may be necessary to provide out-of-the-box capabilities. The purpose of this project is to make up for Paimon's lack of capabilities in this area. Our vision is to make users use Paimon as easy as using a DB system, such as using MySQL. Do it right out of the box.

As a data lake product, Paimon has open features and ecology. Users can use Apache Flink, Spark, or Hive to write data into Paimon, and then query Paimon data through computing engines such as Apache Flink, Spark, Hive, or Trino and Presto, and users can also use MPP engines such as Apache Doris and Starrocks to perform federated queries on the Piamon data lake. There are many choices for users, but for the open ecology of Paimon, there is currently a lack of a unified lake management platform tailored for Paimon, which makes the cost of using Paimon relatively high for users. What we are doing is to provide users with a unified lake management platform tailored only for Paimon, and optimized for Paimon, which greatly reduces the threshold for users to use Paimon as the base of the lake warehouse.

In order to achieve the above goals, we need to provide a visual management system (Paimon Web UI) to lower the threshold for users to use Paimon. The ultimate goal is to enable users to view and manage Paimon data through the UI to achieve a closed loop (Fully UI-driven). Therefore, the capabilities we need to provide are as follows:

-  Write SQL and submit it to the computing engine and visualize the query results
- Manage Paimon's metadata, including creating and persisting Catalog,  creating Paimon tables, viewing Schema, Snapshot, and data file details, etc.
- One-click CDC data entry to the lake, submit the CDC entry task through the form or drag and drop.
- System management, including authority management, tenant management and LDAP authentication, etc.
-  Perfect query and monitoring of various metrics of Paimon
-  Visual display of data lineage
-  Automatic optimization and fault diagnosis, such as merging of small files, etc.

We hope to provide users with platform-based capabilities through the Paimon Web UI, so that Paimon can be used out of the box. Users can use Paimon Web UI as the Paimon data lake management platform, and can also integrate with existing data platforms. At the same time, they can also carry out secondary development on this basis to complete some customized functions, which greatly reduces the threshold for users to use Paimon.

We hope to provide a platform-based ability to submit SQL jobs to the computing engine, but it is bound to Piamon and does not provide a task management platform for a specific computing engine. This is also the boundary of the project, and all the original intentions are In order to make it easier for users to use Paimon.

The project has just started, and there is still a lot to do, and there is a long way to go. At the same time, interested developers are welcome to participate.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by pfdsj-zkx** [comment]
I'm willing to submit a PR!

**Comment by zhu-mingye** [comment]
Is it possible to communicate the above functions through a meeting

**Comment by hdygxsj** [comment]
Can I participate in this project？

**Comment by s7monk** [comment]
> Can I participate in this project？

Your participation is very welcome.

**Comment by s7monk** [comment]
> Is it possible to communicate the above functions through a meeting

After the metadata management function is ready, we can discuss it in the form of an online meeting.
