### ISSUE TITLE
[Feature] Jointly debug user, role, permission, and menu management modules with front-end development

### ISSUE THREAD

**Issue by s7monk** [apache/incubator-paimon-webui#49]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon-webui/issues) and found nothing similar.

### Motivation

At present, the back-end code of users, roles, permissions, and menu management modules is ready and needs to be developed and jointly debugged with the front-end.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by G-XD** [comment]
Hi @s7monk , If you need me anywhere, please feel free to instruct at any time.
