### ISSUE TITLE
[Feature] Support yarn per job mode for paimon web flink submission

### ISSUE THREAD

**Issue by s7monk** [apache/incubator-paimon-webui#58]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon-webui/issues) and found nothing similar.

### Motivation

Currently, we support submission of yarn application mode and need to support yarn per job mode.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by hunter-cloud09** [comment]
I'm interested in this issue and will try to support this feature. Please assign this ticket to me.

**Comment by hunter-cloud09** [comment]
As I know, flink per job mode is not supported in flink1.17, So do you consider not doing this content first?
